apiVersion: v1
kind: Pod
metadata:
  name: examplepodforlabel
  labels:
    environment: prodoction
    app: nginx
    release: stable 
    tire: backend


spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80