apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampledeployforservice
spec:
  replicas: 5
  selector:
    matchLabels:
      example: deployforservice
  template:
    metadata:
      labels:
        example: deployforservice
    spec:
      containers:
      - name : pythonservice
        image: python:3.7
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args: ['echo "<p>The host is $(hostname)</p>" > index.html; python -m http.server 80']
        ports:
        - name: http
          containerPort: 80