apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: exampledaemonset
spec:
  selector:
    matchLabels:
      example: daemonsetforhttpd
  template:
    metadata:
      labels:
        example: daemonsetforhttpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80
          hostPort: 8091
          protocol: TCP