apiVersion: v1
kind: Service
metadata:
  name: exampleheadlessservice
spec:
  selector:   
    example: exampleforservice
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 80
  type: ClusterIP
