apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampledeployforpvc
spec:
  replicas: 2
  selector:
    matchLabels:
      example: exampleforpvc
  template:
    metadata:
      labels:
        example: exampleforpvc
    spec:
      containers:
      - name: containerforpvc
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args: ['echo "The host is $(hostname)" >> /dir/dataforpvc.txt; sleep 3600']
        volumeMounts:
        - name: pvcdata
          mountPath: /dir
      volumes: 
        - name: pvcdata
          persistentVolumeClaim: 
            claimName: examplefornfspvc