apiVersion: v1
kind: Pod
metadata:
  name: "examplepodforlabels"
  namespace: default
  labels:
    app: "nginx"
    environment: "production"
    release: "stable"
    tire: "backend"
spec:
  containers:
  - name: nginx
    imagePullPolicy: IfNotPresent
    image: "nginx"
    ports:
    - containerPort:  80
      name:  http