apiVersion: v1
kind: Pod
metadata:
  name: examplepodforresource
spec:
  containers:
  - name: examplecontainerforresource
    image: vish/stress
    imagePullPolicy: IfNotPresent
    args: ['-mem-total','150Mi','mem-alloc-size','5Mi','-mem-alloc-sleep','1s']
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
      requests:
        memory: "50Mi"
        cpu: "200m"