apiVersion: v1
kind: LimitRange
metadata:
  name: limitrangeforpvc
  namespace: examplenamespace
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: "1Gi"
    min:
      storage: "200Mi"  