apiVersion: v1
kind: LimitRange
metadata:
  name: limitrangeforcontainer
  namespace: examplenamespace
spec:
  limits:
  - max:
      cpu: "200m"
      memory: "300Mi"
    min:
      cpu: "100m"
      memory: "150Mi"
    default:
      cpu: "180m"
      memory: "250Mi"
    defaultRequest:
      cpu: "110m"
      memory: "160Mi"
    type: Container