apiVersion: v1
kind: Pod
metadata:
  name: examplepodforvolumeconfig
spec:
  containers:
  - name: containerforvolume
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh','-c']
    args: ['echo "files:"; ls /config/allvalues; sleep 3600']
    volumeMounts:
    - name: volumeconfig
      mountPath: /config/allvalues
  volumes:
  - name: volumeconfig
    configMap: 
      name: exampleconfigmap