apiVersion: v1
kind: Pod
metadata:
  name: examplepodforvolumeconfig
spec:
  containers:
  - name: containerforvolume
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh','-c']
    args: ['echo "files:"; ls /secret/allvalues; sleep 3600']
    volumeMounts:
    - name: volumesecret
      mountPath: /secret/allvalues
  volumes:
  - name: volumesecret
    secret: 
      secretName: examplesecret