apiVersion: v1
kind: Pod
metadata:
  name: examplepodforimagepullsecret
spec:
  containers:
  - name: example-container
    image:  harbor.gaore.com/tools/python:3.10
    imagePullPolicy: IfNotPresent
    command: ['sh','-c']
    args: ['python --version; sleep 3600']
  imagePullSecrets:
    - name: harbor-secret
