apiVersion: v1
kind: Pod
metadata:
    name: examplepodforport
spec:
    containers:
    - name: containerfornginx
      image: nginx
      imagePullPolicy:  IfNotPresent
      ports:    
      - name: portfoxnginx
        containerPort: 80 
        hostPort: 8081    
        protocol: TCP