apiVersion: v1
kind: Service
metadata:
  name: exampleclusterservice
spec:
  selector:
    example: deployforservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
  type: NodePort